# SPDX-FileCopyrightText: 2024-2025 Kaushlendra Pratap <kaushlendra-pratap.singh@siemens.com>
# SPDX-License-Identifier: GPL-2.0-only
services:
  licensedb:
    container_name: licensedb
    image: "ghcr.io/fossology/licensedb:latest"
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: fossy
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: fossy
      DB_NAME: licensedb
      GIN_MODE: debug
      DEFAULT_ISSUER: http://localhost:8080
      SIMILARITY_THRESHOLD: 0.9
      PORT: 8080
      TOKEN_HOUR_LIFESPAN: 24
      READ_API_AUTHENTICATION_ENABLED: false
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - licensedb-network
  postgres:
    container_name: postgres
    image: "postgres:16"
    environment:
      POSTGRES_PASSWORD: fossy
      POSTGRES_USER: fossy
      POSTGRES_DB: licensedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - licensedb-network
  licensedb-ui:
    container_name: licensedb-ui
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: ghcr.io/fossology/licensedb-ui:latest
    environment:
      REACT_APP_BASE_URL: http://localhost:8080/api/v1
      REACT_APP_DOMAIN_SUBDIRECTORY: ''
      PUBLIC_URL: http://localhost:3000
      REACT_APP_PROVIDER: password
    ports:
      - "3000:3000"
    depends_on:
      licensedb:
        condition: service_healthy
    restart: on-failure
    networks:
      - licensedb-network  
networks:
  licensedb-network:
    driver: bridge
volumes:
  pgdata:


