# SPDX-FileCopyrightText: 2024 Divij Sharma <divijs75@gmail.com>
# SPDX-License-Identifier: GPL-2.0-only

name: Static Checks and Linting

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
        cache: true

    - name: Code Generation
      run: cp external_ref_fields.example.yaml external_ref_fields.yaml && go generate ./...

    - name: lint
      uses: golangci/golangci-lint-action@v6
      with:
          version: v1.62.2

