# SPDX-FileCopyrightText: 2024 Kaushlendra Pratap <kaushlendra-pratap.singh@siemens.com>
# SPDX-License-Identifier: GPL-2.0-only

name: Build and Push Docker Image (Release)

on:
  release:
    types: published

jobs:
  docker-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push release image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/licensedb:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/licensedb:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log out from GHCR
        run: docker logout ghcr.io
